services:
  postgres:
    image: postgres:16
    container_name: pharmacy-postgres
    restart: always
    environment:
      POSTGRES_USER: mina
      POSTGRES_PASSWORD: mina
      POSTGRES_DB: pharmacy
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
